### ISSUE TITLE
Need footer with appropriate information

### ISSUE THREAD

**Issue by jrdemasi** [NCBI-Hackathons/PhenVar#16]
Labeling this as a bug because it was sort of overlooked in the early stages of getting the site up.  We need to add some of the typical branding to the footer.  

@windlust01 or @DCGenomics , this is a standard thing for sites hosted here.  If there's something you'd like us to add or we are required to add since it was developed at the NCBI hackathon, please let us know.

**Comment by CassT** [comment]
Footer has been added
