### ISSUE TITLE
Predictive Search Text

### ISSUE THREAD

**Issue by jrdemasi** [NCBI-Hackathons/PhenVar#17]
As a user starts typing, RSIDs that actually exist should be suggested in the search bar.  If this is too large an ehnacement for v1.2, it can be moved to the v2.0 release.  It may require some retooling of the database or imlpementing of something more robust than sqlite altogether (mongo?)

**Comment by CassT** [comment]
This feature is now implemented in the python3-dev branch.

**Comment by CassT** [comment]
Have merged this change into the live python3 branch
