### ISSUE TITLE
annotate_rsid.py naming

### ISSUE THREAD

**Issue by jrdemasi** [NCBI-Hackathons/PhenVar#2]
The naming of this isn't consistent (so we need to decide on undescore naming or not).  ncbituils -> ncbi_utils? Something like that if we're going in that direction.

**Comment by tanyaphung** [comment]
Sure! Do you have a preference for naming? I've typically use just underscore naming for clarity.

**Comment by jrdemasi** [comment]
So, per pep-8 (which I don't usually strictly follow, but since this is immediately being published, I have been trying) module names should be all lowercase letters and generally as short as possible.  https://www.python.org/dev/peps/pep-0008/

That rules out an "_" also, but again, I'm not that anal about it and willing to change in either direction.

**Comment by tanyaphung** [comment]
Alrighty, that sounds good. We should try to stick to pep-8 as much as possible. So let's stick to naming modules all lowercase letters.
