### ISSUE TITLE
Add number of PMIDs used to generate word cloud

### ISSUE THREAD

**Issue by windlust01** [NCBI-Hackathons/PhenVar#21]
Add a title at the top that say something like '**Word Cloud generated for rs328 from [99 cited PubMed ](https://www.ncbi.nlm.nih.gov/pubmed?Db=pubmed&DbFrom=snp&Cmd=Link&LinkName=snp_pubmed_cited&IdsFromResult=328url)articles**"
![image](https://cloud.githubusercontent.com/assets/16510158/23725449/9f6bafb2-041e-11e7-93ec-c04361dccf50.png)

'99 cited PubMed' should be linked to PubMed using this URL (https://www.ncbi.nlm.nih.gov/pubmed?Db=pubmed&DbFrom=snp&Cmd=Link&LinkName=snp_pubmed_cited&IdsFromResult=328)

**Comment by jrdemasi** [comment]
@windlust01 Check it out!  Let us know if you think that's sufficient.  

JD

**Comment by windlust01** [comment]
Looks good.

**Comment by jrdemasi** [comment]
Implemented in python3 (live) branch.  Thanks, @CassT.
