### ISSUE TITLE
javascript based wordcloud

### ISSUE THREAD

**Issue by jrdemasi** [NCBI-Hackathons/PhenVar#23]
Seems like this project is going in the direction of more interactivity, and it has been shown through benchmarking that the actual generation of the wordcloud is the longest step in searching.  This can also be shown by unchecking the box for generating a cloud (thus, you'll only see the table of words/counts).  

The plan is to implement a javascript based cloud or two in the dev branch first to see how they function and if they'll fulfill our needs, then transition the real site pending approval from the PhenVar team.

**Comment by CassT** [comment]
javascript-based word cloud is now available in the dev branch

**Comment by CassT** [comment]
js-wordcloud thingy is on the main site now.
