### ISSUE TITLE
How to link to PhenVar using rs number or share results?

### ISSUE THREAD

**Issue by windlust01** [NCBI-Hackathons/PhenVar#25]
To promote this resource user should be able to link to it using a rs number or share the link to the results.
Example 1:  Simple link by rs number
https://phenvar.colorado.edu/?rsidInput=rs328
Should populate the search field with rs328 and user select options for output.

Example 2: User knows the output options and wants to link to result page or share the results on social media (Facebook, twitter, etc.).
A) Provide a shared link on the result page, the user can copy and paste.
B) Add social media sharing buttons  (Facebook, twitter, etc.).

**Comment by CassT** [comment]
Added this functionality by changing the search form from POST to GET.
e.g. https://phenvar.colorado.edu/results/?rsids=327+326&visualization=js-wordcloud&visualization=js-graph&normalization_type=article

**Comment by windlust01** [comment]
Thanks.

On Tue, Apr 25, 2017 at 12:11 PM, Cassidy Thompson <notifications@github.com

**Comment by windlust01** [comment]
@CassT  - Can you provide a list of available URL parameters and options?  Thanks.

**Comment by jrdemasi** [comment]
Going to reopen pending documentation for this.  @CassT Happy to help with this sometime this week.

**Comment by CassT** [comment]
I've added the descriptions of the url parameters and usage to the README.
