### ISSUE TITLE
annotate_rsid.py implementation 

### ISSUE THREAD

**Issue by jrdemasi** [NCBI-Hackathons/PhenVar#3]
It looks like this was written to take arguments and run a main function.  If this is standalone from the rest of the project, that's great.  If it's meant to be integrated into the functionality of PhenVar, though, we will need to modify it slightly to utilize the settings.py configuration and strip out some little minutiae.

**Comment by jrdemasi** [comment]
Also, this is not meant to be condemning, and I'm more than happy to help rework this into the project as a whole. Realistically all of it could use a rewrite in an object oriented sense in the future.

**Comment by tanyaphung** [comment]
No problem! Yes, it should be easy to modify. I just wanted to make it work as a standalone function as a first step. But essentially, to incorporate it into the pipeline, we would just need to comment out the unnecessary functions. Thanks!

**Comment by jrdemasi** [comment]
No worries. Just trying to keep things clean and in check

**Comment by tanyaphung** [comment]
I'll update the annotate function now to keep it consistent.
