### ISSUE TITLE
need article_noun_mapping json file

### ISSUE THREAD

**Issue by lisabang** [NCBI-Hackathons/PhenVar#31]
`(base) bash-3.2$ ./manage.py initialize`
`Traceback (most recent call last):`
`  File "./manage.py", line 2, in <module>`
`    from database import initialize_database, load_all_data, load_data_not_present, update_data, build_complete_noun_mapping,\`
`  File "/Users/lbang/PhenVar/database.py", line 142, in <module>`
`    article_noun_mapping = load_noun_mapping()`
`  File "/Users/lbang/PhenVar/database.py", line 127, in load_noun_mapping`
`    with open(MAPPING_FILE, 'r') as json_file:`
`FileNotFoundError: [Errno 2] No such file or directory: 'static/data/article_noun_mapping.json'
`

Just wanted to see if there might be an `article_noun_mapping.json` that I could use to fix this bug.

**Comment by jrdemasi** [comment]
Let me look into this tomorrow. It’s either a file you need to generate and
it’s not documented, or it’s something we have and I’ll put it up somewhere
and fix documentation.

**Comment by CassT** [comment]
You'll want to create the file `static/data/article_noun_mapping.json` with just the contents `{}` . That file can later be populated using `./manage.py build_json` after you've populated the database with `./manage.py load` - the load command will take a ridiculously long time to finish if it still works.
