### ISSUE TITLE
Some additional features that might be nice...

### ISSUE THREAD

**Issue by JohnG-001** [NCBI-Hackathons/PhenVar#6]
Some additional features that might be nice:

-  Option to see words in a list with weights and links, eg:
17           lorem    http://www.lorem.com
16           ipsum    http://www.ipsum.com
13           vitae
…

- Ability to generate using curl for either image or word list

- Method to compare multiple rs numbers, eg
o   Find all rs with a given words or links
o   Compare two or more rs for commonalities and differences

**Comment by jrdemasi** [comment]
Hey @JohnG-001,

Thanks so much for your input.  Some of these features are actually in the works (including an API that would allow you to download a cloud/word list from the CLI).  I'm going to leave this open for now, but may break it down into three or four individual issues and then I will close this original request.  If you want to be sure you own those individual requests, you can resubmit them now (basically each bullet point as a separate issue on GH).  This is just important for when we create milestones, assign out tasks, etc.  

Thanks again!

JD

**Comment by JohnG-001** [comment]
Hi JD,

Done!

Thanks,
John

**Comment by jrdemasi** [comment]
PhenVar team and others: 

This request has been split into three new requests -- [Issue #7 ](https://github.com/NCBI-Hackathons/PhenVar/issues/7), [Issue #8 ](https://github.com/NCBI-Hackathons/PhenVar/issues/8), and [Issue #9 ](https://github.com/NCBI-Hackathons/PhenVar/issues/9)
